### PR TITLE
Update the Node.js version requirements

### PR DESCRIPTION
**Pull request by ronsmith**

### CODE REVIEW

**Comment by Tyriar** [comment]
@ronsmith did something happen in an issue where we started to officially use up to node 16? What is this change based on?

**Comment by ronsmith** [comment]
> @ronsmith did something happen in an issue where we started to officially use up to node 16? What is this change based on?

When I tried to build with node 17, it gave me an error message and explicitly gave me that range. I downgraded to node 16 and it worked just fine

**Comment by Tyriar** [comment]
Normally it takes a bunch of validation across platforms before the team officially moves up a node version. Assigning to @deepak1556 as he's most knowledgeable here now.

**Review by deepak1556 — APPROVED** [review]
Thanks for the PR! requirements were changed as part of https://github.com/microsoft/vscode/pull/142627

**Pull request merged**
