### PR TITLE
Update How-to-Contribute.md

### PR DESCRIPTION
**Pull request by sgharms**
Document the process to get the toolchain up and running in WSL, but also document that it, sadly, will be for naught.

### CODE REVIEW

**Comment by sgharms** [comment]
Documentation change supported by https://github.com/Microsoft/WSL/issues/2293 via https://github.com/Microsoft/vscode/issues/39286#issuecomment-348104428

**Comment by cwegener** [comment]
Let me start by apologizing for hijacking this issue.

I am new to vscode and I saw the issue that you created in the vscode repo about 'building' vscode.

I have been searching high and low through the vscode repository, but I can't for the life of me find any build or run instructions for vscode at all.

I also cloned the 'vscode-wiki' repository but I can't find any instructions on building vscode in here either.

Would you be able to point to the documentation (if any). From your issue that you raised, it seems like you may have some information on how to build and run vscode.

Thanks.

**Comment by cwegener** [comment]
Never mind. I think I just found the markdown file in the vscode-repo! ( ./How-to-Contribute.md )

**Comment by Tyriar** [comment]
I'm not sure this is the right place to call this out since the real underlying problem here is that you cannot launch the Linux version of VS Code via WSL. A simpler "Building and debugging via WSL is not supported" under the Windows section would be better imo as the page is already quite long.

**Pull request closed without merging**
