### PR TITLE
February endgame link

### PR DESCRIPTION
**Pull request by sathishk2030**
I hope changes updated in vscode wiki - https://github.com/microsoft/vscode/wiki/Iteration-Plans

### CODE REVIEW

**Comment by sathishk2030** [comment]
I hope changes reflect on vscode wiki page. 
image
(Above Image:- Outdated informations in vscode wiki page https://github.com/microsoft/vscode/wiki/Iteration-Plans)

**Review by Tyriar — APPROVED** [review]
Thanks again, looks like the job to sync them might have broken, I'll check it out.

**Comment by Tyriar** [comment]
Should be fixed now, ended up breaking as it was running on an older agent that lacked permissions.

**Comment by sathishk2030** [comment]
> Should be fixed now, ended up breaking as it was running on an older agent that lacked permissions.

looking nice 👌

image

**Pull request merged**
