### PR TITLE
Add February iteration plan to wiki page

### PR DESCRIPTION
**Pull request by sjml**

### CODE REVIEW

**Comment by Tyriar** [comment]
Thanks @sjml!

**Comment by sjml** [comment]
Is there a delay or some reason it's not showing up on [the actual page](https://github.com/Microsoft/vscode/wiki/Iteration-Plans)? (Trying to send the link to someone to show the continuing development commitment...)

**Comment by Tyriar** [comment]
Yes it is synced once a day normally, I triggered a manual build since you're waiting.

**Comment by sjml** [comment]
Ah, cool. No worries; sorry to bother you!

**Pull request merged**
