### PR TITLE
Vscode.jason

### PR DESCRIPTION
**Pull request by nutty323**

### CODE REVIEW

**Review by nutty323 — COMMENTED** [review]
Vscode/snippet

**Comment by nutty323** [comment]
Agree

**Review by nutty323 — COMMENTED** [review]
[3_Complete job.txt](https://github.com/microsoft/vscode-wiki/files/9893632/3_Complete.job.txt)

**Review by nutty323 — COMMENTED** [review]
Update

**Comment by Tyriar** [comment]
Spam is bad, please don't spam.

**Pull request closed without merging**
