### PR TITLE
Fix capitalization of GitHub Org

### PR DESCRIPTION
**Pull request by ChaseKnowlden**
Removes Microsoft with capital M from the link.

### CODE REVIEW

**Review by goitf — COMMENTED** [review]
Modified

**Review by goitf — COMMENTED** [review]
modified

**Comment by ChaseKnowlden** [comment]
it was modified

**Comment by Tyriar** [comment]
Thanks for the PR but I suspect this could cause a conflict with our automation which would require manual intervention. Closing since it redirects fine.

**Pull request closed without merging**
